### ISSUE TITLE
Network packaging. 

### ISSUE THREAD

**Issue by Nbrannon** [UCI-UAVForge/GroundStation#1]
Using protobuff and the current network, begin to implement the sending of different kinds of packets to the UAV.  Preferably handled by somebody on Protocol team who has attended meetings.

**Comment by JordanD2** [comment]
I'll have a prototype by the next Protocol meeting.

**Comment by french5033** [comment]
Do we have a prototype for this now?

**Comment by jason-watkins** [comment]
I think @JordanDickson is working on getting the ProtoBuf compiler set up. Once he does, code implementing the protocol serialization/deserialization will be in the [Messaging](https://github.com/UCI-UAVForge/Messaging) repo.

**Comment by jason-watkins** [comment]
Since we're moving away from protobuf, this issue is superseded by #33.
