### ISSUE TITLE
Map Recap Table and Graph

### ISSUE THREAD

**Issue by ghost** [UCI-UAVForge/GroundStation#109]
New GUI:

In the tabbed window, the table and the graph do not appear to load properly.

**Comment by JordanD2** [comment]
I'm not entirely sure how to reproduce this bug. Can you give more details on this?

**Comment by ghost** [comment]
Last time I was running the GUI, I would keep continuing until I hit Map Recap. Then I looked at the tabs and they didn't include the table nor the graph, which was weird. I think some of the problems come from the fact that the old GUI is taken apart in MainMDIDisplay. The issue is that this "dismemberment" process is so complicated that it's difficult to catch weird bugs like this. I've been working on a solution to this.

**Comment by JordanD2** [comment]
I'm also working on the update from Qt 5.4 to 5.7. Early tests don't seem to have bugs like this on the Mac. Maybe there will be similar effects on Windows. Regardless, I think we need to do away with the "dismemberment" method as we move forward. If for nothing else, than just to clean up the project.

**Comment by JordanD2** [comment]
Issue no longer seems relevant in the new GUI is "dismemberment" free.
