### ISSUE TITLE
Simulation

### ISSUE THREAD

**Issue by Nbrannon** [UCI-UAVForge/GroundStation#2]
(Team of two to three people) Need to get a quick and dirty simulation of the UAV to interact with the ground station.  Needs to be able to receive the various kinds of packets being sent to the UAV, and using a command line be able to send back the kind of Packets were expecting. See protocol notes for more information on the kinds of packets and storage of data. (This is not in the current project, and needs to be its own exe)

**Comment by kphan4** [comment]
I will attempt this

**Comment by JordanD2** [comment]
The simulator design details have changed a bit, but #92 effectively closes this.
