### ISSUE TITLE
Use consistent styling and positioning for interface elements

### ISSUE THREAD

**Issue by aarcane** [UCI-UAVForge/GroundStation#24]
I've found square and curved buttons, as well as buttons that look nothing like other buttons, and buttons split above and below elements, taking up entire rows and columns of layouts, etc.  A single layout and style should be settled upon for buttons and other interactive elements
This is a sub issue of #3

**Comment by m1771vw** [comment]
Layouts are affected by different versions of Windows/Mac. What you see on Windows 7, you won't see the same thing on Win8 & Win10. Not really sure how to fix this problem

**Comment by jason-watkins** [comment]
@aarcane Is there additional work that can be accomplished on this issue, or are the remaining inconsistencies a result of QT's cross-platform variations?

**Comment by JordanD2** [comment]
Many GUI of the worst inconsistencies between OS's were fixed in Qt 5.7 in #114. The new display style will address the issues of button textures and inconsistency. Checks on this will be done in #130.
