### ISSUE TITLE
Integrate custom packet code from Avionics Repository

### ISSUE THREAD

**Issue by jason-watkins** [UCI-UAVForge/GroundStation#33]
My custom serialization code is now in the Avionics repo [here](https://github.com/UCI-UAVForge/Avionics/tree/master/Coordinator). You will need all of the files that have "Packet" in the name. The ground station team should be able to integrate this code in place of protobuf with minimal work.

After copying files over to the ground station repo, you should just need to replace calls to `Serial` with whatever the ground station uses for error handling and replace `String` with `std::string`.

**Comment by jason-watkins** [comment]
Note that this issue supersedes #1.

**Comment by Nbrannon** [comment]
Is the supposed to be no AckPacket.cpp?  And can we just remove "Arduino.h" and include the necessary c/c++headers?

**Comment by jason-watkins** [comment]
Yes and yes. The `AckPacket` doesn't contain any additional data over the base `Packet`, so it's entirely implemented in the header.

**Comment by Nbrannon** [comment]
On line 69 of info packet, you call other.getBytes(buffer + 6, len, offset + 6).  
the only String.getBytes() function i can find on the arduino reference is two arguments, String.getBytes(buf,len) .  Is there somewhere you can point me where this function is defined?

**Comment by jason-watkins** [comment]
`String` is an Arduino type. You'll need to replace it with `std::string` or QT strings or whatever and find an equivalent method for those types.

**Comment by JordanD2** [comment]
Avionics team is no longer maintaining the Packet Library. The most recent version is now in the GroundStation repo.
