### ISSUE TITLE
Mission Execution data presentation

### ISSUE THREAD

**Issue by Nbrannon** [UCI-UAVForge/GroundStation#5]
Need fields to display last known speed and XYZ of UAV

**Comment by aarcane** [comment]
Got this mostly done, how to calculate appropriate speed units from a pair of points xyz and time delta in ms?  What are the appropriate speed units?

**Comment by Nbrannon** [comment]
You dont need to calculate speed,  it will be given by the uav.  My guess
would be kph for now

**Comment by jason-watkins** [comment]
Actually, assume m/s. I'm not 100% sure what the raw data will be, but we will almost certainly use m/s for internal calculations on the UAV, and we will send it to the ground station in whatever the UAV uses internally.
