### ISSUE TITLE
Update splash screen

### ISSUE THREAD

**Issue by Nbrannon** [UCI-UAVForge/GroundStation#7]
Change splash screen to new logo and make it so it doesnt pop up in full screen, rather a small window like other software (Word, visual studio.)  It scares Nathan.

**Comment by aarcane** [comment]
In order to complete this, the correct image is needed, and any specific sizing constraints need to be documented.

**Comment by Nbrannon** [comment]
The logo has been moved to the Ground station folder of the UAV google drive, was given to us as an illustrator file, need somebody to export it.

**Comment by mcraven** [comment]
Closed by #14
