### ISSUE TITLE
Support for Qt 5.5+

### ISSUE THREAD

**Issue by JordanD2** [UCI-UAVForge/GroundStation#77]
In Qt 5.5 and greater, support for QWebKit was dropped in favor of QWebEngine. WebEngine seems to have some advantages over WebKit for linking JavaScript and C++ together. Migrating our code base from WebKit to WebEngine would also allow us to use supported code and the newer versions of Qt.

**Comment by logicxd** [comment]
So should we move back to using 5.7?

**Comment by JordanD2** [comment]
Eventually we will have support for 5.7, but for now I think we have to use 5.4.

**Comment by JordanD2** [comment]
Breakthrough! Ok I found an easy way to convert all our QWebKit code into QWebEngine code. It's really messy right now, but I think I can have this converted by Friday.

**Comment by logicxd** [comment]
I don't have QT installed ATM. Does this mean I should go ahead and install the latest one?

**Comment by JordanD2** [comment]
Yes, you should download/install Qt 5.7. Once we upgrade, 5.4 and younger will no longer be usable because QWebKit was deprecated in 5.5. I would maybe hold off on 5.8 pre-release for now.

**Comment by JordanD2** [comment]
Closed by #114
