### ISSUE TITLE
Mission Planning Dialog

### ISSUE THREAD

**Issue by logicxd** [UCI-UAVForge/GroundStation#79]
I tried to implement what was drawn on the paper for the mission planning part.

<img width="338" alt="screen shot 2016-10-14 at 11 43 14 pm" src="https://cloud.githubusercontent.com/assets/12219300/19408062/f47bb754-9268-11e6-93c9-414e78588aab.png">

Is this okay?

**Comment by JordanD2** [comment]
The layout looks good to me.
