### ISSUE TITLE
SQL Database for Storing Missions, FlightPaths, and other data

### ISSUE THREAD

**Issue by JordanD2** [UCI-UAVForge/GroundStation#82]
We currently have no way of saving mission data to the disk. An SQL database would allow us to save and load mission flightpaths, mission results, and UAV statistics. An SQL database that can store numbers, floats, and strings is sufficient to close this issue. Integration and expansion will be done at a later time.

**Comment by logicxd** [comment]
Whoever's working on database, I can provide sommmmme help. Learning it atm.

**Comment by JordanD2** [comment]
I believe @fa01 (aka Rayan) is working on this. I'll go ahead and assign you both on it.

**Comment by fa01** [comment]
Yeah, I've been working on this.

**Comment by logicxd** [comment]
Are you coming tomorrow? Let's sync up and see where I can help.

**Comment by logicxd** [comment]
<img width="979" alt="screen shot 2016-10-28 at 11 31 11 pm" src="https://cloud.githubusercontent.com/assets/12219300/19827784/9e4be65e-9d69-11e6-9c3a-61e71b17cb8d.png">

Got a working database 👍 
What are the variables that you want? 
List of current missions : **mission name** (string), **ID** (integer). 
Flight Paths: **ID** (integer), **latitude**(float), **longitude** (float), **altitude** (float).
Mission Results: **ID** (integer), ???
UAV Stats: **ID** (integer), ???

**Comment by JordanD2** [comment]
@logicxd We'll talk at the meeting about how to move forward from here. I think the next step is just to implement the serialization/deserialization methods for each of the items we want to store, but first I want to make sure that our database is as flexible as possible.

Note: Implementation will be part of (multiple?) future issues. Most likely one per object-type

**Comment by JordanD2** [comment]
Table demonstration at the meeting met all of the requirements of this Issue. A pull request that adds the sample code to a new folder in the root directory can close this issue.
