### ISSUE TITLE
Selecting an item in the Mission Planner MDI window's combo box crashes the program

### ISSUE THREAD

**Issue by JordanD2** [UCI-UAVForge/GroundStation#86]
After a few minutes of testing, I think this is because of dereferencing a null pointer in the setExecutionButtonEnabled() method.

**Comment by JordanD2** [comment]
@Roman-Parise @logicxd

According to the comments, you guys worked on this part of the code. Maybe you guys have some idea on what is causing this bug and/or how to fix it? I think it's because "executeButton->setEnabled(false)" is running when executeButton is null. Maybe we can start our bug-hunt there.

**Comment by ghost** [comment]
That specific function has been commented out. We originally had a separate execute button in that window, but took it out. That button had a function that would prevent you from executing a mission if you hadn't selected anything from the ComboBox. However, that execute button is essentially removed and replaced by the buttons from the MissionPlanning GUI.

**Comment by logicxd** [comment]
Sorry I just got back home.

Yeah what Roman said is correct, the ComboBox was implemented on it's own. The idea for that "executedButton->setEnabled(false)" was that if nothing is selected from the ComboBox, then the button would be disabled until something is selected.

**Comment by JordanD2** [comment]
Fixed by #87
