### ISSUE TITLE
Migration from Google Maps to Leaflet

### ISSUE THREAD

**Issue by JordanD2** [UCI-UAVForge/GroundStation#93]
After the demonstration of the new Leaflet based MissionPlanning map, we're going to migrate the rest of the program to using the Leaflet API. As we migrate, keep in mind the goal of shifting towards the use of a single javascript file for mission planning, execution, and recap.

**Comment by tantiwup** [comment]
Should I make a pull request for this?

**Comment by JordanD2** [comment]
Yes. Once the mission planning, execution, and recap are using all the same javascript file with the leaflet API, then a pull request would be great.

**Comment by JordanD2** [comment]
Closed by #139
