### ISSUE TITLE
Load and Save buttons on Mission Planning GUI

### ISSUE THREAD

**Issue by JordanD2** [UCI-UAVForge/GroundStation#95]
With the SQL database coming together soon, we need GUI that supports the ability to save and load missions from disk. A pull request that adds such buttons along with empty functions is sufficient to close this issue. Making the functions actually save and load data will be done at a later time.

**Comment by ghost** [comment]
Buttons are there! :D

**Comment by JordanD2** [comment]
Closed by #97
