### ISSUE TITLE
New GUI Exit Button

### ISSUE THREAD

**Issue by ghost** [UCI-UAVForge/GroundStation#96]
In the new GUI, if you transition from Planning to Execution to Recap and then back to Planning, clicking the Exit button causes the program to crash.

**Comment by JordanD2** [comment]
This is kind of a shot in the dark, but I suspect this is cause by the Planning, Execution, and Recap windows failing to properly dispose of their resources (Timer Threads, Network Ports, etc) when we change windows.

**Comment by ghost** [comment]
It appears this issue has been remedied. Fix coming in a pull request soon...
